### PR TITLE
Add more proofs

### PR DESCRIPTION
**Pull request by karmanyaahm**
To avoid having too many pull requests I'll add a few platforms in this one.
- Gitlab
- Hackernews
- dev.to

### CODE REVIEW

**Review by shombando — COMMENTED** [review]
@karmanyaahm thanks for adding these proofs. I checked https://keyoxide.org/4AF679D0ABA0ED4B07BF7B6932CA3267C8D187D7 to see if you were able to test these successfully but I don't see it. Can you please confirm these are tested and I will approve the merge. Please @ mention me. Thanks again!

**Comment by karmanyaahm** [comment]
I'm actually testing these on https://keyoxide.org/772E634E9358415B1393DD9D081D3D4FBA896372 which is a separate revoked key just for testing. I'll inform you for the merge as soon as I get dev.to done later today.

**Comment by karmanyaahm** [comment]
@shombando I think the changes are good now.

**Comment by shombando** [comment]
Great work @karmanyaahm, thanks for your many contributions. I'm going to some minor clean-up and mark update to version 0.3.0 thanks to your proof support expansion.

**Pull request merged**
