### PR TITLE
Add Reddit proof support

### PR DESCRIPTION
**Pull request by karmanyaahm**

### CODE REVIEW

**Comment by shombando** [comment]
Thanks for the PR @karmanyaahm. I'll review this weekend, I really appreciate you taking the time to add proofs.
I've actually moved main further since your PR (I was focused on adding/deleting proofs and didn't get the PR notification). Could you please pull main, resolve conflicts, and update the PR?
If not no worries, I'll cherry pick and merge this weekend. Thanks again!

**Review by shombando — CHANGES_REQUESTED** [review]
Please pull in main, more info in comment.

**Comment by karmanyaahm** [comment]
I pulled main and removed the `===` part.

**Comment by shombando** [comment]
@karmanyaahm Thanks for the PR, I really appreciate it!

**Pull request merged**
